<?php

/**
 * @file
 * Flexible Image Gallery module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flexible_image_gallery_help(string $route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.flexible_image_gallery') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Creates a custom content type to display a gallery of media images in a lovely, flexible grid.') . '</p>';
    $output .= '<p>' . t('To learn more or report issues, ') . '<a href="https://github.com/kistasaurus/flexible_image_gallery/" target="_blank">' . t('visit the Github repo') . '</a>.</p>';
    return $output;
  }
}

/**
 * Implements hook_theme().
 */
function flexible_image_gallery_theme($existing, $type, $theme, $path) {
  return [
    'field__field_flexible_gallery' => [
      'base hook' => 'field',
      'template' => 'field--field-flexible-gallery',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Allow gap to be adjusted.
 */
function flexible_image_gallery_preprocess_html(&$variables) {
  $config = \Drupal::config('flexible_image_gallery.settings');

  // Process gap configurations to get it in units
  $config_gap = $config->get('gap') ?? 1;
  $config_gap_unit = $config->get('gap_unit') ?? 0;
  if ($config_gap_unit === 1) {
    $gap_unit = "em";
  } elseif ($config_gap_unit === 2) {
    $gap_unit = "px";
  } else {
    $gap_unit = "rem";
  }
  $gap = $config_gap . $gap_unit;

  // Process margin configurations to get them in units
  $config_margin_top = $config->get('margin_top') ?? 1;
  $config_margin_bottom = $config->get('margin_bottom') ?? 1;
  $config_margin_unit = $config->get('margin_unit') ?? 0;
  if ($config_margin_unit === 1) {
    $margin_unit = "em";
  } elseif ($config_margin_unit === 2) {
    $margin_unit = "px";
  } else {
    $margin_unit = "rem";
  }
  $margin_top = $config_margin_top . $margin_unit;
  $margin_bottom = $config_margin_bottom . $margin_unit;

  $variables['html_attributes']->setAttribute('style', "--fig-gap:$gap;--fig-margin-top:$margin_top;--fig-margin-bottom:$margin_bottom;");
}
