<?php

/**
 * @file
 * Flexible Image Gallery module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flexible_image_gallery_help(string $route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.flexible_image_gallery') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Creates a custom content type to display a gallery of media images in a lovely, flexible grid.') . '</p>';
    $output .= '<p>' . t('To learn more or report issues, ') . '<a href="https://github.com/kistasaurus/flexible_image_gallery/" target="_blank">' . t('visit the Github repo') . '</a>.</p>';
    return $output;
  }
}

/**
 * Implements hook_theme().
 */
function flexible_image_gallery_theme($existing, $type, $theme, $path) {
  return [
    'field__field_flexible_gallery' => [
      'base hook' => 'field',
      'template' => 'field--field-flexible-gallery',
    ],
  ];
}
